GET http://localhost:5000/users

###
GET http://localhost:5000/users/64c21e5a9064be376db6dcc0

###
POST http://localhost:5000/users
Content-Type: application/json

{
    "name": "ahaha",
    "email": "alana@gmail.com",
    "gender": "Male"
}

###
PATCH http://localhost:5000/users/64c21df09064be376db6dcbd
Content-Type: application/json

{
    "name": "broooooooo",
    "email": "sdfsdfsdf@gmail.com",
    "gender": "Male"
}

###
DELETE http://localhost:5000/users/64c21df09064be376db6dcbd
Content-Type: application/json

###
GET http://localhost:5000/videos/64c294e149210e219b3b7bf3/comment

###
POST http://localhost:5000/videos
Content-Type: application/json

{
  "videoID": "itnqEauWQZM",
  "videoThumbnail": "https://www.gamespot.com/a/uploads/original/1601/16018044/4134965-beast-1.jpg",
  "videoTitle": "Transformers: Rise of The Beasts",
  "product": [
    {
      "productLink": "https://www.youtube.com/watch?v=5qap5aO4i9A",
      "productTitle": "mongoose",
      "productPrice": 1000
    },
    {
      "productLink": "https://www.youtube.com/watch?v=5qap5aO4i9A",
      "productTitle": "express",
      "productPrice": 2000
    },
    {
      "productLink": "https://www.youtube.com/watch?v=5qap5aO4i9A",
      "productTitle": "mongodb",
      "productPrice": 3000
    }
  ],
  "comment": [
    {
      "commentUsername": "alana",
      "commentContent": "good"
    },
    {
      "commentUsername": "alana",
      "commentContent": "good"
    },
    {
      "commentUsername": "alana",
      "commentContent": "good"
    }
  ]
}

###
PATCh http://localhost:5000/videos/64c294e149210e219b3b7bf3/comment
Content-Type: application/json

{
        "commentUsername": "Aldo",
        "commentContent": "Anjayyy"
}
